// <auto-generated />
using CSharp5Lap45.Data.EF.DBContext;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace CSharp5Lap45.Data.Migrations
{
    [DbContext(typeof(DBContextFPOLY))]
    partial class DBContextFPOLYModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.6")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("CSharp5Lap45.Data.EF.Entity.FClass", b =>
                {
                    b.Property<int>("IdClass")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("NameClass")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("IdClass");

                    b.ToTable("FClass");

                    b.HasData(
                        new
                        {
                            IdClass = 1,
                            NameClass = "Lop 1"
                        },
                        new
                        {
                            IdClass = 2,
                            NameClass = "Lop 2"
                        },
                        new
                        {
                            IdClass = 3,
                            NameClass = "Lop 3"
                        });
                });

            modelBuilder.Entity("CSharp5Lap45.Data.EF.Entity.FStudent", b =>
                {
                    b.Property<int>("StId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("IdClass")
                        .HasColumnType("int");

                    b.Property<float>("Mark")
                        .HasColumnType("real");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("StId");

                    b.HasIndex("IdClass");

                    b.ToTable("FStudent");

                    b.HasData(
                        new
                        {
                            StId = 1,
                            Email = "st1@gmail.com",
                            IdClass = 1,
                            Mark = 5f,
                            Name = "Dungna1"
                        },
                        new
                        {
                            StId = 2,
                            Email = "st2@gmail.com",
                            IdClass = 2,
                            Mark = 7f,
                            Name = "Dungna2"
                        },
                        new
                        {
                            StId = 3,
                            Email = "st3@gmail.com",
                            IdClass = 3,
                            Mark = 2f,
                            Name = "Dungna3"
                        },
                        new
                        {
                            StId = 4,
                            Email = "st4@gmail.com",
                            IdClass = 1,
                            Mark = 10f,
                            Name = "Dungna4"
                        },
                        new
                        {
                            StId = 5,
                            Email = "SV5@gmail.com",
                            IdClass = 3,
                            Mark = 8f,
                            Name = "Dungna5"
                        });
                });

            modelBuilder.Entity("CSharp5Lap45.Data.EF.Entity.FStudent", b =>
                {
                    b.HasOne("CSharp5Lap45.Data.EF.Entity.FClass", "FClass")
                        .WithMany("FStudents")
                        .HasForeignKey("IdClass")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("FClass");
                });

            modelBuilder.Entity("CSharp5Lap45.Data.EF.Entity.FClass", b =>
                {
                    b.Navigation("FStudents");
                });
#pragma warning restore 612, 618
        }
    }
}
